baseURL = "https://henrycabral.me"
languageCode = "en-us"
DefaultContentLanguage = "en"

pygmentsCodefences = true
pygmentsStyle = "manni"

paginate = 20

title = "henry cabral"
theme = "flamingo"
[markup.goldmark.renderer]
unsafe = true

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

publishDir = "docs"


[menu]

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 10

  [[menu.secondary]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10

  [[menu.secondary]]
    identifier = "resume"
    name = "resume"
    url = "https://github.com/mrprofessor/resume/blob/master/rudra_kar_resume.pdf/"
    weight = 11

  [[menu.secondary]]
    identifier = "logs"
    name = "logs"
    url = "/logs/"
    weight = 12


[params]
  author = "Henry Cabral"
  description = "When "
  sitename = "Henry Cabral's Blog"
  github = "https://github.com/cabralh"
  twitter = "@cabralhjr"
  favicon = "/images/favicon.ico"
  # resume = "https://docs.google.com/gview?url=https://github.com/mrprofessor/resume/raw/master/rudra_narayan_resume.pdf&embedded=true"
  resume = "https://github.com/mrprofessor/resume/blob/master/rudra_narayan_resume.pdf"
  mainSections = "posts"


# Projects list
[[params.projects]]
  name = "solitude"
  description = "A git based note taking application. 📚"
  demoLink = "https://solitudenote.github.io/solitude/"
  sourceLink = "https://github.com/solitudenote/solitude"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
